# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import cloudevents_pb2 as cloudevents__pb2

GRPC_GENERATED_VERSION = "1.64.1"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in cyoda_cloud_api_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class CloudEventsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.startStreaming = channel.stream_stream(
            "/org.cyoda.cloud.api.grpc.CloudEventsService/startStreaming",
            request_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
            response_deserializer=cloudevents__pb2.CloudEvent.FromString,
            _registered_method=True,
        )
        self.entityModelManage = channel.unary_unary(
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entityModelManage",
            request_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
            response_deserializer=cloudevents__pb2.CloudEvent.FromString,
            _registered_method=True,
        )
        self.entityManage = channel.unary_unary(
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entityManage",
            request_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
            response_deserializer=cloudevents__pb2.CloudEvent.FromString,
            _registered_method=True,
        )
        self.entityManageCollection = channel.unary_stream(
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entityManageCollection",
            request_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
            response_deserializer=cloudevents__pb2.CloudEvent.FromString,
            _registered_method=True,
        )
        self.entitySearch = channel.unary_unary(
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entitySearch",
            request_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
            response_deserializer=cloudevents__pb2.CloudEvent.FromString,
            _registered_method=True,
        )
        self.entitySearchCollection = channel.unary_stream(
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entitySearchCollection",
            request_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
            response_deserializer=cloudevents__pb2.CloudEvent.FromString,
            _registered_method=True,
        )


class CloudEventsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def startStreaming(self, request_iterator, context):
        """
        API for calculation externalization:


        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def entityModelManage(self, request, context):
        """
        API for managing models:



        Following event pairs supported:
        Input: EntityModelImportRequest, Output: EntityModelImportResponse
        Input: EntityModelExportRequest, Output: EntityModelExportResponse
        Input: EntityModelTransitionRequest, Output: EntityModelTransitionResponse
        Input: EntityModelDeleteRequest, Output: EntityModelDeleteResponse
        Input: EntityModelGetAllRequest, Output: EntityModelGetAllResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def entityManage(self, request, context):
        """
        API for managing entities:



        Following event pairs supported:
        Input: EntityCreateRequest, Output: EntityTransactionResponse
        Input: EntityUpdateRequest, Output: EntityTransactionResponse
        Input: EntityDeleteRequest, Output: EntityDeleteResponse
        Input: EntityTransitionRequest, Output: EntityTransitionResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def entityManageCollection(self, request, context):
        """
        Following event pairs supported:
        Input: EntityDeleteAllRequest, Output: EntityDeleteAllResponse
        Input: EntityCreateCollectionRequest, Output: EntityTransactionResponse
        Input: EntityUpdateCollectionRequest, Output: EntityTransactionResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def entitySearch(self, request, context):
        """
        API for searching entities:



        Following event pairs supported:
        Input: EntitySnapshotSearchRequest, Output: EntitySnapshotSearchResponse
        Input: SnapshotGetStatusRequest, Output: EntitySearchResponse
        Input: SnapshotCancelRequest, Output: EntitySearchResponse
        Input: EntityGetRequest, Output: EntityResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def entitySearchCollection(self, request, context):
        """
        Following event pairs supported:
        Input: EntityGetAllRequest, Output: EntityResponse
        Input: SnapshotGetRequest, Output: EntityResponse
        Input: EntitySearchRequest, Output: EntityResponse
        Input: EntityStatsGetRequest, Output: EntityStatsResponse
        Input: EntityStatsByStateGetRequest, Output: EntityStatsByStateResponse
        Input: EntityChangesMetadataGetRequest, Output: EntityChangesMetadataResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CloudEventsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "startStreaming": grpc.stream_stream_rpc_method_handler(
            servicer.startStreaming,
            request_deserializer=cloudevents__pb2.CloudEvent.FromString,
            response_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
        ),
        "entityModelManage": grpc.unary_unary_rpc_method_handler(
            servicer.entityModelManage,
            request_deserializer=cloudevents__pb2.CloudEvent.FromString,
            response_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
        ),
        "entityManage": grpc.unary_unary_rpc_method_handler(
            servicer.entityManage,
            request_deserializer=cloudevents__pb2.CloudEvent.FromString,
            response_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
        ),
        "entityManageCollection": grpc.unary_stream_rpc_method_handler(
            servicer.entityManageCollection,
            request_deserializer=cloudevents__pb2.CloudEvent.FromString,
            response_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
        ),
        "entitySearch": grpc.unary_unary_rpc_method_handler(
            servicer.entitySearch,
            request_deserializer=cloudevents__pb2.CloudEvent.FromString,
            response_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
        ),
        "entitySearchCollection": grpc.unary_stream_rpc_method_handler(
            servicer.entitySearchCollection,
            request_deserializer=cloudevents__pb2.CloudEvent.FromString,
            response_serializer=cloudevents__pb2.CloudEvent.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "org.cyoda.cloud.api.grpc.CloudEventsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "org.cyoda.cloud.api.grpc.CloudEventsService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CloudEventsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def startStreaming(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/org.cyoda.cloud.api.grpc.CloudEventsService/startStreaming",
            cloudevents__pb2.CloudEvent.SerializeToString,
            cloudevents__pb2.CloudEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def entityModelManage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entityModelManage",
            cloudevents__pb2.CloudEvent.SerializeToString,
            cloudevents__pb2.CloudEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def entityManage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entityManage",
            cloudevents__pb2.CloudEvent.SerializeToString,
            cloudevents__pb2.CloudEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def entityManageCollection(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entityManageCollection",
            cloudevents__pb2.CloudEvent.SerializeToString,
            cloudevents__pb2.CloudEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def entitySearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entitySearch",
            cloudevents__pb2.CloudEvent.SerializeToString,
            cloudevents__pb2.CloudEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def entitySearchCollection(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/org.cyoda.cloud.api.grpc.CloudEventsService/entitySearchCollection",
            cloudevents__pb2.CloudEvent.SerializeToString,
            cloudevents__pb2.CloudEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
