from pydantic import Field
from common.entity.cyoda_entity import CyodaEntity

class RiskEvent(CyodaEntity):
    """
    An event generated by the risk monitoring system when a predefined risk limit is breached.
    """
    ENTITY_NAME = "risk_event"
    ENTITY_VERSION = "1"

    portfolio_id: str = Field(..., description="The ID of the portfolio where the risk event occurred.")
    breached_limit: str = Field(..., description="The name of the breached risk limit.")
    details: str = Field(..., description="Details about the risk event.")
    timestamp: int = Field(..., description="The time of the event.")