from pydantic import Field, BaseModel
from common.entity.cyoda_entity import CyodaEntity
import datetime
from enum import Enum

class RiskLevel(str, Enum):
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"

class RiskEvent(CyodaEntity):
    """
    An event generated by the risk monitoring system when a predefined risk limit is breached.
    """

    # Constants
    ENTITY_NAME: str = "RiskEvent"
    ENTITY_VERSION: int = 1

    # Business ID
    event_id: str = Field(..., description="Unique identifier for the risk event.", example="RKE-2025-12-15-00001")

    # Event Fields
    portfolio_id: str = Field(..., description="The portfolio where the risk event occurred.", example="PORT-001")
    risk_type: str = Field(..., description="The type of risk that was breached.", example="PositionLimit")
    level: RiskLevel = Field(..., description="The severity level of the event.")
    message: str = Field(..., description="A description of the risk event.", example="Position limit exceeded for AAPL.")
    details: dict = Field(..., description="A dictionary containing detailed context about the event.")
    timestamp: datetime.datetime = Field(..., description="Timestamp of when the event was triggered.")
